package com.propcycle.app.data.scanner;

import androidx.annotation.NonNull;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.JsonParser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;

/**
 * Immutable, validated result returned by the smart scanner.
 *
 * <p>The model's JSON is never exposed directly to the UI. All text, enum, collection, and
 * numeric fields pass through the bounds in this class first.</p>
 */
public final class ScanAnalysis {

    public static final int MAX_JSON_CHARACTERS = 8_192;
    public static final int MAX_ITEM_NAME_CHARACTERS = 80;
    public static final int MAX_MATERIAL_CHARACTERS = 80;
    public static final int MAX_GUIDANCE_CHARACTERS = 500;
    public static final int MAX_IDEA_CHARACTERS = 180;
    public static final int MAX_ENVIRONMENTAL_NOTE_CHARACTERS = 300;
    public static final int MAX_SAFETY_NOTE_CHARACTERS = 300;
    public static final int MIN_UPCYCLING_IDEAS = 1;
    public static final int MAX_UPCYCLING_IDEAS = 3;

    /** Fixed application copy; it is not generated by, or alterable by, the model. */
    public static final String MALAYSIA_DISCLAIMER =
            "AI identification is only a general estimate. Recycling rules differ across "
                    + "Malaysia, so check your local council or recycling centre before disposal.";

    private static final Set<String> REQUIRED_JSON_FIELDS = Collections.unmodifiableSet(
            new HashSet<>(Arrays.asList(
                    "itemName",
                    "material",
                    "category",
                    "isRecyclable",
                    "uncalibratedModelEstimatePercent",
                    "recyclingGuidance",
                    "upcyclingIdeas",
                    "environmentalNote",
                    "safetyNote")));

    private static final Gson JSON_WRITER = new GsonBuilder().disableHtmlEscaping().create();

    private final String itemName;
    private final String material;
    private final Category category;
    private final boolean recyclable;
    private final int uncalibratedModelEstimatePercent;
    private final String recyclingGuidance;
    private final List<String> upcyclingIdeas;
    private final String environmentalNote;
    private final String safetyNote;

    public ScanAnalysis(
            @NonNull String itemName,
            @NonNull String material,
            @NonNull Category category,
            boolean recyclable,
            int uncalibratedModelEstimatePercent,
            @NonNull String recyclingGuidance,
            @NonNull List<String> upcyclingIdeas,
            @NonNull String environmentalNote,
            @NonNull String safetyNote) {
        this.itemName = requireBoundedText(
                itemName, "itemName", MAX_ITEM_NAME_CHARACTERS);
        this.material = requireBoundedText(
                material, "material", MAX_MATERIAL_CHARACTERS);
        this.category = Objects.requireNonNull(category, "category");
        this.recyclable = recyclable;
        if (uncalibratedModelEstimatePercent < 0
                || uncalibratedModelEstimatePercent > 100) {
            throw new ValidationException(
                    "uncalibratedModelEstimatePercent must be between 0 and 100.");
        }
        this.uncalibratedModelEstimatePercent = uncalibratedModelEstimatePercent;
        this.recyclingGuidance = requireBoundedText(
                recyclingGuidance, "recyclingGuidance", MAX_GUIDANCE_CHARACTERS);
        this.upcyclingIdeas = validateIdeas(upcyclingIdeas);
        this.environmentalNote = requireBoundedText(
                environmentalNote,
                "environmentalNote",
                MAX_ENVIRONMENTAL_NOTE_CHARACTERS);
        this.safetyNote = requireBoundedText(
                safetyNote, "safetyNote", MAX_SAFETY_NOTE_CHARACTERS);
    }

    /** Parses only the scanner's expected JSON object and rejects missing or extra fields. */
    @NonNull
    public static ScanAnalysis fromJson(@NonNull String json) {
        Objects.requireNonNull(json, "json");
        if (json.trim().isEmpty()) {
            throw new ValidationException("The AI response is empty.");
        }
        if (json.length() > MAX_JSON_CHARACTERS) {
            throw new ValidationException("The AI response is too large.");
        }

        final JsonObject object;
        try {
            JsonElement root = JsonParser.parseString(json);
            if (!root.isJsonObject()) {
                throw new ValidationException("The AI response must be one JSON object.");
            }
            object = root.getAsJsonObject();
        } catch (JsonParseException | IllegalStateException malformedJson) {
            throw new ValidationException("The AI response is not valid JSON.", malformedJson);
        }

        Set<String> actualFields = new HashSet<>();
        object.keySet().forEach(actualFields::add);
        if (!actualFields.equals(REQUIRED_JSON_FIELDS)) {
            throw new ValidationException("The AI response has missing or unexpected fields.");
        }

        try {
            JsonArray ideasJson = requireArray(object, "upcyclingIdeas");
            List<String> ideas = new ArrayList<>(ideasJson.size());
            for (JsonElement idea : ideasJson) {
                if (!idea.isJsonPrimitive() || !idea.getAsJsonPrimitive().isString()) {
                    throw new ValidationException("Each upcycling idea must be text.");
                }
                ideas.add(idea.getAsString());
            }

            return new ScanAnalysis(
                    requireString(object, "itemName"),
                    requireString(object, "material"),
                    Category.fromWireValue(requireString(object, "category")),
                    requireBoolean(object, "isRecyclable"),
                    requireInteger(object, "uncalibratedModelEstimatePercent"),
                    requireString(object, "recyclingGuidance"),
                    ideas,
                    requireString(object, "environmentalNote"),
                    requireString(object, "safetyNote"));
        } catch (NumberFormatException | UnsupportedOperationException | IllegalStateException error) {
            throw new ValidationException("The AI response contains a value of the wrong type.", error);
        }
    }

    /** Serializes the already-validated result for a bounded Navigation argument. */
    @NonNull
    public String toJson() {
        JsonObject object = new JsonObject();
        object.addProperty("itemName", itemName);
        object.addProperty("material", material);
        object.addProperty("category", category.name());
        object.addProperty("isRecyclable", recyclable);
        object.addProperty(
                "uncalibratedModelEstimatePercent", uncalibratedModelEstimatePercent);
        object.addProperty("recyclingGuidance", recyclingGuidance);
        JsonArray ideas = new JsonArray();
        for (String idea : upcyclingIdeas) {
            ideas.add(idea);
        }
        object.add("upcyclingIdeas", ideas);
        object.addProperty("environmentalNote", environmentalNote);
        object.addProperty("safetyNote", safetyNote);
        return JSON_WRITER.toJson(object);
    }

    @NonNull
    public String getItemName() {
        return itemName;
    }

    @NonNull
    public String getMaterial() {
        return material;
    }

    @NonNull
    public Category getCategory() {
        return category;
    }

    public boolean isRecyclable() {
        return recyclable;
    }

    /** This value is model self-reporting, not a calibrated probability. */
    public int getUncalibratedModelEstimatePercent() {
        return uncalibratedModelEstimatePercent;
    }

    @NonNull
    public String getRecyclingGuidance() {
        return recyclingGuidance;
    }

    @NonNull
    public List<String> getUpcyclingIdeas() {
        return upcyclingIdeas;
    }

    @NonNull
    public String getEnvironmentalNote() {
        return environmentalNote;
    }

    @NonNull
    public String getSafetyNote() {
        return safetyNote;
    }

    @NonNull
    private static List<String> validateIdeas(@NonNull List<String> values) {
        Objects.requireNonNull(values, "upcyclingIdeas");
        if (values.size() < MIN_UPCYCLING_IDEAS || values.size() > MAX_UPCYCLING_IDEAS) {
            throw new ValidationException("upcyclingIdeas must contain between 1 and 3 items.");
        }
        List<String> cleanValues = new ArrayList<>(values.size());
        for (String value : values) {
            cleanValues.add(requireBoundedText(
                    value, "upcyclingIdeas", MAX_IDEA_CHARACTERS));
        }
        return Collections.unmodifiableList(cleanValues);
    }

    @NonNull
    private static String requireBoundedText(
            @NonNull String value,
            @NonNull String fieldName,
            int maxCharacters) {
        Objects.requireNonNull(value, fieldName);
        String cleanValue = normalizeWhitespace(value);
        if (cleanValue.isEmpty()) {
            throw new ValidationException(fieldName + " must not be empty.");
        }
        if (cleanValue.length() > maxCharacters) {
            throw new ValidationException(fieldName + " is too long.");
        }
        String lowerCaseValue = cleanValue.toLowerCase(Locale.ROOT);
        if (lowerCaseValue.contains("http://")
                || lowerCaseValue.contains("https://")
                || lowerCaseValue.contains("www.")) {
            throw new ValidationException(fieldName + " must not contain a web link.");
        }
        return cleanValue;
    }

    @NonNull
    private static String normalizeWhitespace(@NonNull String value) {
        StringBuilder clean = new StringBuilder(value.length());
        boolean previousWasWhitespace = true;
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            if (Character.isISOControl(character) || Character.isWhitespace(character)) {
                if (!previousWasWhitespace) {
                    clean.append(' ');
                    previousWasWhitespace = true;
                }
            } else {
                clean.append(character);
                previousWasWhitespace = false;
            }
        }
        int length = clean.length();
        if (length > 0 && clean.charAt(length - 1) == ' ') {
            clean.deleteCharAt(length - 1);
        }
        return clean.toString();
    }

    @NonNull
    private static String requireString(@NonNull JsonObject object, @NonNull String name) {
        JsonElement value = object.get(name);
        if (value == null
                || !value.isJsonPrimitive()
                || !value.getAsJsonPrimitive().isString()) {
            throw new ValidationException(name + " must be text.");
        }
        return value.getAsString();
    }

    private static boolean requireBoolean(@NonNull JsonObject object, @NonNull String name) {
        JsonElement value = object.get(name);
        if (value == null || !value.isJsonPrimitive()) {
            throw new ValidationException(name + " must be true or false.");
        }
        if (value.getAsJsonPrimitive().isBoolean()) {
            return value.getAsBoolean();
        }
        // firebase-ai 17.15.0 exposes the Kotlin JVM method named `boolean`, which Java
        // source cannot call because it is a keyword. The response schema therefore uses
        // an exact two-value string enum, while navigation serialization remains a JSON boolean.
        if (value.getAsJsonPrimitive().isString()) {
            String text = value.getAsString();
            if ("true".equals(text)) {
                return true;
            }
            if ("false".equals(text)) {
                return false;
            }
        }
        throw new ValidationException(name + " must be true or false.");
    }

    private static int requireInteger(@NonNull JsonObject object, @NonNull String name) {
        JsonElement value = object.get(name);
        if (value == null
                || !value.isJsonPrimitive()
                || !value.getAsJsonPrimitive().isNumber()) {
            throw new ValidationException(name + " must be a whole number.");
        }
        String rawValue = value.getAsString();
        if (!rawValue.matches("-?(0|[1-9][0-9]*)")) {
            throw new ValidationException(name + " must be a whole number.");
        }
        return Integer.parseInt(rawValue);
    }

    @NonNull
    private static JsonArray requireArray(@NonNull JsonObject object, @NonNull String name) {
        JsonElement value = object.get(name);
        if (value == null || !value.isJsonArray()) {
            throw new ValidationException(name + " must be a list.");
        }
        return value.getAsJsonArray();
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof ScanAnalysis)) {
            return false;
        }
        ScanAnalysis that = (ScanAnalysis) other;
        return recyclable == that.recyclable
                && uncalibratedModelEstimatePercent
                == that.uncalibratedModelEstimatePercent
                && itemName.equals(that.itemName)
                && material.equals(that.material)
                && category == that.category
                && recyclingGuidance.equals(that.recyclingGuidance)
                && upcyclingIdeas.equals(that.upcyclingIdeas)
                && environmentalNote.equals(that.environmentalNote)
                && safetyNote.equals(that.safetyNote);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                itemName,
                material,
                category,
                recyclable,
                uncalibratedModelEstimatePercent,
                recyclingGuidance,
                upcyclingIdeas,
                environmentalNote,
                safetyNote);
    }

    public enum Category {
        RECYCLABLE("Recyclable"),
        COMPOSTABLE("Compostable"),
        REUSABLE("Reusable"),
        E_WASTE("E-waste"),
        HAZARDOUS("Hazardous waste"),
        GENERAL_WASTE("General waste"),
        UNKNOWN("Unknown");

        private final String displayName;

        Category(@NonNull String displayName) {
            this.displayName = displayName;
        }

        @NonNull
        public String getDisplayName() {
            return displayName;
        }

        @NonNull
        private static Category fromWireValue(@NonNull String value) {
            try {
                return Category.valueOf(value.trim().toUpperCase(Locale.ROOT));
            } catch (IllegalArgumentException unknownCategory) {
                throw new ValidationException("category is not supported.", unknownCategory);
            }
        }
    }

    public static final class ValidationException extends IllegalArgumentException {
        public ValidationException(@NonNull String message) {
            super(message);
        }

        public ValidationException(@NonNull String message, @NonNull Throwable cause) {
            super(message, cause);
        }
    }
}
